# Generated by Django 4.1.2 on 2023-09-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student01_is_verified_student01_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student01',
            name='mobile_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
