# Generated by Django 4.1.2 on 2023-09-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student01_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student01',
            name='mobile_number',
            field=models.CharField(max_length=100),
        ),
    ]
