# Generated by Django 4.1.2 on 2023-09-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student01',
            name='phoneNumber',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
