# Generated by Django 4.1.2 on 2023-09-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student01_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student01',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='student01',
            name='user_phone',
            field=models.TextField(default=10, max_length=100),
        ),
    ]
