# Generated by Django 4.1.2 on 2023-09-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_student01_phone_number_student01_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student01',
            name='user_phone',
        ),
    ]
