# Generated by Django 4.1.2 on 2023-09-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_student01_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student01',
            name='phoneNumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
