# Generated by Django 4.1.2 on 2023-09-06 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0013_remove_student01_email_remove_student01_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student01',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student01',
            name='first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='student01',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student01',
            name='last_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='student01',
            name='password',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='student01',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student01',
            name='user_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='student01',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='student01',
            name='phoneNumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
