# Generated by Django 4.1.2 on 2023-09-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_studentupdate_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student01',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='studentupdate',
            name='user_phone',
            field=models.CharField(default=6370997812, max_length=15),
            preserve_default=False,
        ),
    ]
