# Generated by Django 4.1.2 on 2023-09-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_student01_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentupdate',
            name='user_phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
