# Generated by Django 4.1.2 on 2023-09-07 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0018_alter_studentupdate_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentupdate',
            name='user_phone',
        ),
        migrations.AlterField(
            model_name='studentupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
