# Generated by Django 4.1.2 on 2023-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_mobile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_user',
            name='user_mobile',
            field=models.CharField(max_length=15),
        ),
    ]
