# Generated by Django 4.1.2 on 2023-09-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_delete_mobile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentupdate',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
