# Generated by Django 4.1.2 on 2023-09-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_studentupdate_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student01',
            name='phone_number',
            field=models.CharField(default=6370997812, max_length=15),
            preserve_default=False,
        ),
    ]
