# Generated by Django 4.1.2 on 2023-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_student01_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentupdate',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
