# Generated by Django 4.1.2 on 2023-09-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_studentupdate_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentupdate',
            name='user_name',
        ),
    ]
