# Generated by Django 4.1.2 on 2023-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_remove_studentupdate_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentupdate',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
