# Generated by Django 4.1.2 on 2023-09-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_studentupdate_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentupdate',
            old_name='mobile_number',
            new_name='user_mobile',
        ),
    ]
