# Generated by Django 4.1.2 on 2023-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_rename_mobile_number_studentupdate_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student01',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student01',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student01',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student01',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
